services:
  - type: web
    name: world-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: worldchat
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
